config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount SolidErrors::Engine, at: "/errors"

  mount Litestream::Engine, at: "/litestream"

  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "sla_rules#index"

  resources :sla_rules
end

app/models/action_log.rb
class ActionLog < ApplicationRecord
  validates :issue_id, :action_type, :action_details, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/linear_label.rb
class LinearLabel < ApplicationRecord
end

app/models/linear_state.rb
class LinearState < ApplicationRecord
end

app/models/sla_rule.rb
class SlaRule < ApplicationRecord
  enum :action_type, {
    comment: 0,
    update_status: 1,
    update_priority: 2
  }

  enum :filter_type, {
    priority: 0,
    label: 1,
    state: 2
  }

  validates :filter_type, :filter_value, :inactive_duration, :action_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/mission_control/base_controller.rb
module MissionControl
  mattr_writer :username
  mattr_writer :password

  class << self
    # use method instead of attr_accessor to ensure
    # this works if variable set after SolidErrors is loaded
    def username
      @username ||= @@username || ENV.fetch("MISSION_CONTROL_USERNAME", "admin")
    end

    def password
      @password ||= @@password || ENV.fetch("MISSION_CONTROL_PASSWORD", SecureRandom.hex(16))
    end
  end

  class BaseController < ActionController::Base
    protect_from_forgery with: :exception

    http_basic_authenticate_with name: MissionControl.username, password: MissionControl.password
  end
end

app/controllers/sla_rules_controller.rb
class SlaRulesController < ApplicationController
  before_action :set_sla_rule, only: [ :edit, :update, :destroy ]

  def index
    @sla_rules = SlaRule.all
  end

  def new
    @sla_rule = SlaRule.new
  end

  def create
    @sla_rule = SlaRule.new(sla_rule_params)

    if @sla_rule.save
      redirect_to sla_rules_path
    else
      render :new
    end
  end

  def edit
    @sla_rule = SlaRule.find(params[:id])
  end

  def update
    if @sla_rule.update(sla_rule_params)
      redirect_to sla_rules_path
    else
      render :edit
    end
  end

  def destroy
    @sla_rule.destroy
    redirect_to sla_rules_path
  end

  private

  def sla_rule_params
    params.require(:sla_rule).permit(:filter_type, :filter_value, :inactive_duration, :action_type, :action_details)
  end

  def set_sla_rule
    @sla_rule = SlaRule.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sla_rules_helper.rb
module SlaRulesHelper
  def render_action_details(form, rule)
    if rule.action_type == "comment"
      form.text_area :action_details, class: "form-control", placeholder: "Enter comment to add"
    elsif rule.action_type == "update_status"
      form.select :action_details, LinearState.pluck(:name, :name), {}, class: "form-control"
    elsif rule.action_type == "update_priority"
      form.select :action_details, Linear::PRIORITY.map { |priority, value| [ priority, value ] }, {}, class: "form-control"
    end
  end

  def filter_type_text(rule)
    case rule.filter_type
    when "priority"
      "Priority"
    when "label"
      "Has Label"
    when "state"
      "Has Status"
    end
  end

  def filter_value_text(rule)
    if rule.filter_type == "priority"
      Linear::PRIORITY.invert[rule.filter_value.to_i]
    else
      rule.filter_value
    end
  end

  def action_details_text(rule)
    if rule.action_type == "update_priority"
      Linear::PRIORITY.invert[rule.action_details.to_i]
    else
      rule.action_details
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Linear Sla" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container py-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sla_rules/_form.html.erb
<%= form_with(model: @sla_rule, html: {data: {controller: "sla-form"}}) do |form| %>
  <% if @sla_rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sla_rule.errors.count, "error") %> prohibited this sla_rule from being saved:</h2>

      <ul>
      <% @sla_rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :filter_type %>
    <%= form.select :filter_type, options_for_select([['Has Status', 'state'], ['Has Label', 'label'], ['Priority', 'priority']], @sla_rule.filter_type), {}, class: "form-select",  data: { action: "change->sla-form#filterTypeChanged", "sla-form-target" => "filterType" }  %>
  </div>

  <div class="mb-3">
    <%= form.label :filter_value %>
    <%= form.select :filter_value, Linear::PRIORITY.to_a, {}, id: 'priority_select_field', class: "form-select filter-value-options", "data-filter-type" => "priority" %>
    <%= form.select :filter_value, LinearState.pluck(:name, :name), {}, id: 'state_select_field', class: "form-select filter-value-options", "data-filter-type" => "state" %>
    <%= form.select :filter_value, LinearLabel.pluck(:name, :name), {}, id: 'label_select_field', class: "form-select filter-value-options", "data-filter-type" => "label" %>
  </div>

  <div class="mb-3">
    <%= form.label :inactive_duration, "Inactive Duration (in Hours)" %>
    <%= form.text_field :inactive_duration, class: "form-control" %>
  </div>
  
  <div class="mb-3">
    <%= form.label :action_type %>
    <%= form.select :action_type, options_for_select([['Add Comment', 'comment'], ['Update Status to', 'update_status'], ['Update Priority to', 'update_priority']], @sla_rule.action_type), {}, class: "form-select", data: { action: "change->sla-form#actionTypeChanged", "sla-form-target" => "actionType" } %>
  </div>
  
  <div class="mb-3">
    <%= form.label :action_details %>
    <%= form.text_field :action_details, class: "form-control action-details-options", "data-action-type" => "comment", placeholder: "Enter comment here" %>
    <%= form.select :action_details, Linear::PRIORITY.to_a, {}, id: 'priority_select_field', class: "form-select action-details-options", "data-action-type" => "update_priority" %>
    <%= form.select :action_details, LinearState.pluck(:name, :name), {}, id: 'state_select_field', class: "form-select action-details-options", "data-action-type" => "update_status" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sla_rules/edit.html.erb
<h1>Edit SLA Rule</h1>

<%= render "form" %>

<%= link_to 'Back', sla_rules_path %>

app/views/sla_rules/index.html.erb
<h1>SLA Rules</h1>
<table class="table">
  <tr>
    <th>Filter Type</th>
    <th>Filter Value</th>
    <th>Inactive Duration (Hours)</th>
    <th>Action Type</th>
    <th>Action details</th>
    <th>Actions</th>
  </tr>
  
  <% @sla_rules.each do |sla_rule| %>
    <tr>
      <td><%= filter_type_text(sla_rule) %></td>
      <td><%= filter_value_text(sla_rule) %></td>
      <td><%= sla_rule.inactive_duration %></td>
      <td><%= sla_rule.action_type %></td>
      <td><%= action_details_text(sla_rule) %></td>
      <td>
        <%= link_to 'Edit', edit_sla_rule_path(sla_rule) %>
        <%= link_to 'Delete', sla_rule, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Sla Rule', new_sla_rule_path %>

app/views/sla_rules/new.html.erb
<h1>New SLA rule</h1>

<%= render "form" %>

<%= link_to 'Back', sla_rules_path %>